### ISSUE TITLE
Consider higher speed

### ISSUE THREAD

**Issue by zeeqeeng** [SJYssr/chaoxing#2]
- 配置文件 config.ini 里我注意到倍速 speed 注释提到其值最大为2，请问这是出于什么考量？
- 我个人尝试将 speed 值更改为大于2比如16，发现倍速仍为2倍速，请问能解决高倍速刷课需求吗？

**Comment by SJYssr** [comment]
高倍速的话容易被平台清空，老师是可以看到后台的时间的，平台也有检测，风险比较高
